// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::FlatBuffers;

public struct CSCreateRole : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static CSCreateRole GetRootAsCSCreateRole(ByteBuffer _bb) { return GetRootAsCSCreateRole(_bb, new CSCreateRole()); }
  public static CSCreateRole GetRootAsCSCreateRole(ByteBuffer _bb, CSCreateRole obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public CSCreateRole __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string NickName { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNickNameBytes() { return __p.__vector_as_span(4); }
#else
  public ArraySegment<byte>? GetNickNameBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetNickNameArray() { return __p.__vector_as_array<byte>(4); }
  public RoleGender Gender { get { int o = __p.__offset(6); return o != 0 ? (RoleGender)__p.bb.GetSbyte(o + __p.bb_pos) : RoleGender.Male; } }
  public int Clothes(int j) { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(__p.__vector(o) + j * 4) : (int)0; }
  public int ClothesLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<byte> GetClothesBytes() { return __p.__vector_as_span(8); }
#else
  public ArraySegment<byte>? GetClothesBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public int[] GetClothesArray() { return __p.__vector_as_array<int>(8); }

  public static Offset<CSCreateRole> CreateCSCreateRole(FlatBufferBuilder builder,
      StringOffset NickNameOffset = default(StringOffset),
      RoleGender Gender = RoleGender.Male,
      VectorOffset ClothesOffset = default(VectorOffset)) {
    builder.StartObject(3);
    CSCreateRole.AddClothes(builder, ClothesOffset);
    CSCreateRole.AddNickName(builder, NickNameOffset);
    CSCreateRole.AddGender(builder, Gender);
    return CSCreateRole.EndCSCreateRole(builder);
  }

  public static void StartCSCreateRole(FlatBufferBuilder builder) { builder.StartObject(3); }
  public static void AddNickName(FlatBufferBuilder builder, StringOffset NickNameOffset) { builder.AddOffset(0, NickNameOffset.Value, 0); }
  public static void AddGender(FlatBufferBuilder builder, RoleGender Gender) { builder.AddSbyte(1, (sbyte)Gender, 0); }
  public static void AddClothes(FlatBufferBuilder builder, VectorOffset ClothesOffset) { builder.AddOffset(2, ClothesOffset.Value, 0); }
  public static VectorOffset CreateClothesVector(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateClothesVectorBlock(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartClothesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<CSCreateRole> EndCSCreateRole(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<CSCreateRole>(o);
  }
};

public struct SCCreateRole : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static SCCreateRole GetRootAsSCCreateRole(ByteBuffer _bb) { return GetRootAsSCCreateRole(_bb, new SCCreateRole()); }
  public static SCCreateRole GetRootAsSCCreateRole(ByteBuffer _bb, SCCreateRole obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public SCCreateRole __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public CommonErrorCode ErrorCode { get { int o = __p.__offset(4); return o != 0 ? (CommonErrorCode)__p.bb.GetSbyte(o + __p.bb_pos) : CommonErrorCode.Success; } }
  public string NickName { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNickNameBytes() { return __p.__vector_as_span(6); }
#else
  public ArraySegment<byte>? GetNickNameBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetNickNameArray() { return __p.__vector_as_array<byte>(6); }
  public string UID { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetUIDBytes() { return __p.__vector_as_span(8); }
#else
  public ArraySegment<byte>? GetUIDBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetUIDArray() { return __p.__vector_as_array<byte>(8); }
  public int Clothes(int j) { int o = __p.__offset(10); return o != 0 ? __p.bb.GetInt(__p.__vector(o) + j * 4) : (int)0; }
  public int ClothesLength { get { int o = __p.__offset(10); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<byte> GetClothesBytes() { return __p.__vector_as_span(10); }
#else
  public ArraySegment<byte>? GetClothesBytes() { return __p.__vector_as_arraysegment(10); }
#endif
  public int[] GetClothesArray() { return __p.__vector_as_array<int>(10); }

  public static Offset<SCCreateRole> CreateSCCreateRole(FlatBufferBuilder builder,
      CommonErrorCode ErrorCode = CommonErrorCode.Success,
      StringOffset NickNameOffset = default(StringOffset),
      StringOffset UIDOffset = default(StringOffset),
      VectorOffset ClothesOffset = default(VectorOffset)) {
    builder.StartObject(4);
    SCCreateRole.AddClothes(builder, ClothesOffset);
    SCCreateRole.AddUID(builder, UIDOffset);
    SCCreateRole.AddNickName(builder, NickNameOffset);
    SCCreateRole.AddErrorCode(builder, ErrorCode);
    return SCCreateRole.EndSCCreateRole(builder);
  }

  public static void StartSCCreateRole(FlatBufferBuilder builder) { builder.StartObject(4); }
  public static void AddErrorCode(FlatBufferBuilder builder, CommonErrorCode ErrorCode) { builder.AddSbyte(0, (sbyte)ErrorCode, 0); }
  public static void AddNickName(FlatBufferBuilder builder, StringOffset NickNameOffset) { builder.AddOffset(1, NickNameOffset.Value, 0); }
  public static void AddUID(FlatBufferBuilder builder, StringOffset UIDOffset) { builder.AddOffset(2, UIDOffset.Value, 0); }
  public static void AddClothes(FlatBufferBuilder builder, VectorOffset ClothesOffset) { builder.AddOffset(3, ClothesOffset.Value, 0); }
  public static VectorOffset CreateClothesVector(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateClothesVectorBlock(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartClothesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<SCCreateRole> EndSCCreateRole(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<SCCreateRole>(o);
  }
};

